### PR TITLE
Add additional functionality to the CSS library

### PR DESCRIPTION
**Pull request by chrismamo1**
I added optional arguments to a few functions in the CSS library, documenting them appropriately. They all use optional arguments, so it shouldn't break any existing code. I also added a new gradient generator, which supports both linear and radial gradients.

### CODE REVIEW

**Comment by dsheets** [comment]
This looks useful. Thanks!

Unfortunately, there are a few issues which should be cleared up before merging:

1. The project no longer builds under OCaml 4.00.1 due to the use of `@@` in `css.ml`.
2. Could you indent `polygradient` like the rest of the code in the library? Right now, it is indented pretty far. `ocp-indent` can help with this.
3. Does there need to be a non-vendor-prefixed line in the implementation of `gradient`?

**Comment by avsm** [comment]
Regarding 1), it's probably a reasonable time to make Cow a 4.01+ project only, unless there are any remaining upstream dependencies which make it worth maintaining support?

**Comment by samoht** [comment]
Thanks for the patch. All the functions should have a non-optional argument as last argument, otherwise partial application is broken (e.g. `()`). I'm fine if that means breaking the API.

**Comment by chrismamo1** [comment]
I don't think that these changes broke the API, since `make tests` still passes.

**Comment by chrismamo1** [comment]
It looks like the builds keeps failing because of a failure to download "index files", not because of an actual build failure. Should I just keep submitting tiny commits until the downloads start succeeding?

**Comment by chrismamo1** [comment]
I should probably create a new pull request now that I've started modifying the HTML library as well. Would any of you recommend that?

**Comment by samoht** [comment]
I'm happy to make a 1.3.0 release with you changes (no need to create a new PR). Can you make your patches compile on 4.00 (`# Error: Unbound value |>`)?

**Comment by samoht** [comment]
And can you rebase your branch to remove the merge commits? Thanks!

**Comment by chrismamo1** [comment]
My apologies, I'm not great at Git. Still trying to fix the excessive merge commits issue mentioned by @samoht

**Comment by chrismamo1** [comment]
I'm having some trouble with Git, and my efforts to fix the problem seem to have led to many repetitive commit messages. Any suggestions?

**Comment by samoht** [comment]
don't worry with that then, I'll do it later.

**Comment by chrismamo1** [comment]
@samoht Thank you very much. I'll make a separate branch so I can keep working without further mucking things up in this PR before the release.

**Comment by samoht** [comment]
Superseded by #78
